### ISSUE TITLE
over-lapping

### ISSUE THREAD

**Issue by haniali1234** [geekwise-kevin-kears/fresnovdp#3]
@haniali1234
-header images are over lapping. 
-add more stuff to the footer.
- All your css files needs to be in the CSS folder and delete unnecessarily files.

**Comment by geekwise-kevin-kears** [comment]
working on it now

**Comment by geekwise-kevin-kears** [comment]
fixed header need to reposition the donate button as well

**Comment by geekwise-kevin-kears** [comment]
closing, will keep the footer issue open until resolved
